version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=crud
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: django
    build: .
    command: python manage.py migrate --noinput
    depends_on:
      db:
        condition: service_healthy

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db





